import { chromium } from 'playwright-core';
const S = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, reducedMotion: 'reduce' });
const p = await ctx.newPage();
await p.goto('http://localhost:4321/ru/', { waitUntil: 'networkidle' });
await p.screenshot({ path: `${S}/u_banner.png` });
await p.click('[data-cc="manage"]'); await p.waitForTimeout(300);
await p.screenshot({ path: `${S}/u_prefs.png` });
await p.click('[data-cc-prefs] [data-cc="reject"]');
await p.click('[data-menu-open]'); await p.waitForTimeout(400);
await p.screenshot({ path: `${S}/u_menu.png` });
await p.keyboard.press('Escape');
await p.evaluate(() => document.querySelectorAll('[data-reveal]').forEach((e) => e.classList.add('is-in')));
await p.locator('#packages .pk__rail').scrollIntoViewIfNeeded(); await p.evaluate(() => window.scrollBy(0, -60)); await p.waitForTimeout(500);
await p.screenshot({ path: `${S}/u_pk.png` });
await p.goto('http://localhost:4321/ru/poluchit-predlozhenie/', { waitUntil: 'networkidle' });
await p.fill('#lead-offer-address', 'Рига'); await p.click('#lead-offer [data-next]'); await p.click('#lead-offer [data-next]'); await p.waitForTimeout(300);
await p.screenshot({ path: `${S}/u_form.png` });
await b.close();
